{
  id: 'saudi_convo_p10_old_friend_reunion',
  phase: 10,
  title: 'Old Friend Reunion',
  description: 'You run into a childhood friend you haven\'t seen in years. Navigate warmth, surprise, and catching up.',
  focalWordIds: ['w_tadhakkara', 'w_remember', 'w_zaman', 'w_friend', 'w_hayaa', 'w_wallah', 'w_khalas', 'w_yaani'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'والله العظيم! أنت؟ ما صدّقت — كم سنة ما شفناك يا أخي!', translation: 'I swear to God! You? I can\'t believe it — how many years since we\'ve seen you, brother!', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Respond to your old friend\'s surprise. Match his warmth.', options: [
      { text: 'والله يا عمي! زمان والله، اشتقت لك كثير', translation: 'By God, man! It\'s been ages, I really missed you.', nextStepId: 's3', correct: true, feedback: 'Perfect — زمان والله hits the right register of warm Saudi reunion.' },
      { text: 'أيوه، مرحبا. كيف الحال؟', translation: 'Yeah, hi. How are you?', nextStepId: 's3', correct: false, feedback: 'Too flat — this is an old friend. A reunion needs more warmth than a passing greeting.' },
      { text: 'نعم، مررت من هنا بالصدفة.', translation: 'Yes, I happened to pass by here.', nextStepId: 's3', correct: false, feedback: 'Way too formal and cold. Your friend is overwhelmed with joy — match that energy.' },
      { text: 'هلا هلا! الله يسلمك، ما غيّرت أبد!', translation: 'Hey hey! God keep you safe, you haven\'t changed at all!', nextStepId: 's3', correct: true, feedback: 'Excellent — هلا هلا and the compliment land beautifully for a reunion.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'ابن الواوي! كأنها بالأمس لما كنّا نلعب في الحارة. وين صرت هالأيام؟', translation: 'Jackpot! It\'s like yesterday when we used to play in the neighbourhood. Where have you been these days?', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Tell him briefly where life has taken you.', options: [
      { text: 'الرياض، شغل وعيلة، خلاص يعني — الحياة مشت', translation: 'Riyadh, work and family, that\'s it really — life moved on.', nextStepId: 's5', correct: true, feedback: 'خلاص يعني is exactly right here — resigned, warm, real.' },
      { text: 'انتقلت إلى الرياض للعمل منذ خمس سنوات.', translation: 'I moved to Riyadh for work five years ago.', nextStepId: 's5', correct: false, feedback: 'Too formal — this is your childhood friend, not an HR interview.' },
      { text: 'ما تسأل، يا عمي. السفر والشغل أكلوا العمر.', translation: 'Don\'t ask, man. Travel and work ate up the years.', nextStepId: 's5', correct: true, feedback: 'Natural and idiomatic — ما تسأل is a perfect opener for life stories.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'الله يعين. أنا كذلك، ما بقي وقت لشي. بس على بال الأيام القديمة دايماً في القلب.', translation: 'God help us. Me too, no time for anything anymore. But those old days are always on the heart.', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'He mentions the old days are always on his heart. Respond genuinely.', options: [
      { text: 'صحيح، الذكريات ما تموت أبداً.', translation: 'True, memories never die.', nextStepId: 's7', correct: true, feedback: 'Simple and heartfelt — fits the mood perfectly.' },
      { text: 'على بال — تلك الأيام لن تعود.', translation: 'On the heart — those days won\'t come back.', nextStepId: 's7', correct: false, feedback: 'Too melancholic and stiff. You\'re celebrating the reunion, not mourning the past.' },
      { text: 'إي والله، يا ريت نرجع لتلك الأيام. ما كان فيها هموم.', translation: 'Yes by God, if only we could go back. No worries back then.', nextStepId: 's7', correct: true, feedback: 'يا ريت lands beautifully — nostalgic, warm, and very Saudi.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'تعال نتغدى سوا اليوم، ما أقبل عذر. اتصل على شلّتنا القديمة كذلك!', translation: 'Come, let\'s have lunch together today — I won\'t accept any excuse. Call the old gang too!', next: 's8' },
    { id: 's8', speaker: 'user', prompt: 'Accept his invitation warmly.', options: [
      { text: 'حاضر يا عمي، ما يهمّك — أنا معاك.', translation: 'Ready, man — don\'t worry about it, I\'m with you.', nextStepId: 's9', correct: true, feedback: 'ما يهمّك is perfect here — a warm, committed acceptance.' },
      { text: 'نعم، سأحضر إذا كان لدي وقت.', translation: 'Yes, I\'ll come if I have time.', nextStepId: 's9', correct: false, feedback: 'Too conditional and formal. Your old friend just said he won\'t accept excuses — don\'t give him one.' },
      { text: 'زين، بس لا تتأخر عليّ.', translation: 'Fine, but don\'t be late on me.', nextStepId: 's9', correct: false, feedback: 'Wrong tone entirely — he\'s inviting you, not the other way around.' },
    ]},
    { id: 's9', speaker: 'partner', text: 'الله يخليك! خلاص يعني، اليوم نكمّل الذكريات. زمان ما اجتمعنا كذا.', translation: 'God keep you! That\'s it then, today we complete the memories. It\'s been forever since we gathered like this.', end: true },
  ],
  completionMessage: 'Excellent! You navigated a warm Saudi reunion with the right idioms, tone, and code-switching. ابن الواوي!',
},

{
  id: 'saudi_convo_p10_argue_with_brother',
  phase: 10,
  title: 'Argue With Your Brother',
  description: 'A heated but loving argument with your older brother over a decision you\'ve made.',
  focalWordIds: ['w_brother', 'w_opinion', 'w_think', 'w_because', 'w_haqq', 'w_wallah', 'w_khalas', 'w_angry'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'أنت مجنون ولا إيش؟ كيف تقدر تترك الشغل بدون ما تشاورني؟!', translation: 'Are you crazy or what? How can you leave the job without consulting me?!', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Defend yourself without being disrespectful to your older brother.', options: [
      { text: 'يا أخي، أنا كبرت. قراري قراري، ما عندك دعوة.', translation: 'Brother, I\'m grown up. My decision is my decision, it\'s none of your business.', nextStepId: 's3', correct: false, feedback: 'Too sharp and dismissive — with an older brother, you can assert yourself without cutting him off completely.' },
      { text: 'والله يا أخوي، ما قدرت أكمل هناك — حاولت أصبر وما قدرت.', translation: 'By God, brother, I couldn\'t continue there — I tried to be patient and couldn\'t.', nextStepId: 's3', correct: true, feedback: 'Good — والله يا أخوي opens with warmth while still being honest.' },
      { text: 'هذا الأمر لا يعنيك على الإطلاق.', translation: 'This matter doesn\'t concern you at all.', nextStepId: 's3', correct: false, feedback: 'Way too cold and formal. This is your brother — even in argument, family bonds require softer framing.' },
      { text: 'سامعني يا أخوي، الوضع ما كان يطاق. ما بخبّرك؟', translation: 'Hear me out, brother — the situation was unbearable. Wasn\'t I going to tell you?', nextStepId: 's3', correct: true, feedback: 'Perfect — سامعني asserts yourself while keeping the door open.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'ما بخبّرني؟! أنا أخوك الكبير — مسؤوليتي عليك. كان لازم تجي عندي أول.', translation: 'You weren\'t going to tell me?! I\'m your older brother — I\'m responsible for you. You should have come to me first.', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Acknowledge his concern without fully backing down.', options: [
      { text: 'أعرف يا أخوي، وأنا أقدّر هذا. بس أحياناً الإنسان يحتاج يقرر لحاله.', translation: 'I know, brother, and I appreciate that. But sometimes a person needs to decide for himself.', nextStepId: 's5', correct: true, feedback: 'Balanced and mature — you honour his role while asserting your autonomy.' },
      { text: 'أنت مو مسؤول عني. أنا ما طفل.', translation: 'You\'re not responsible for me. I\'m not a child.', nextStepId: 's5', correct: false, feedback: 'Too aggressive — you\'re escalating rather than resolving. Wrong tone for a family argument that should end with reconciliation.' },
      { text: 'معك حق، كان يجب أن أستشيرك أولاً.', translation: 'You\'re right, I should have consulted you first.', nextStepId: 's5', correct: false, feedback: 'You\'re caving completely — this kills the honest dialogue. Stand your ground with warmth.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'والله العظيم ما أزعل عليك، بس يؤلمني لما أشوف أخوي يتعب بصمت.', translation: 'I swear to God I\'m not angry at you, but it hurts me when I see my brother struggling in silence.', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'The argument is softening. Reach toward him.', options: [
      { text: 'يا أخوي، والله ما قصّدت أذيّك. أنت أهم واحد عندي.', translation: 'Brother, by God I didn\'t mean to hurt you. You\'re the most important person to me.', nextStepId: 's7', correct: true, feedback: 'This is the right move — vulnerability at the right moment resolves family conflict.' },
      { text: 'خلاص يعني، انتهى الموضوع. نتكلم بعدين.', translation: 'That\'s it, topic\'s over. We\'ll talk later.', nextStepId: 's7', correct: false, feedback: 'You\'re shutting the door just as it opened. خلاص here is avoidance, not resolution.' },
      { text: 'إذا كنت تزعل، فأنا آسف.', translation: 'If you\'re upset, then I\'m sorry.', nextStepId: 's7', correct: false, feedback: 'A conditional apology is not an apology. It sounds defensive, not warm.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'خلاص يعني، أنا معك مهما كان. بس المرة الجاية — كلّمني أول. ما يهمّك، نحلّها سوا.', translation: 'Alright then, I\'m with you no matter what. But next time — call me first. Don\'t worry, we\'ll solve it together.', end: true },
  ],
  completionMessage: 'You handled a charged family argument with the right blend of assertion and warmth. حق وصدق!',
},

{
  id: 'saudi_convo_p10_grandfather_story',
  phase: 10,
  title: 'Grandfather\'s Story',
  description: 'Your grandfather is sharing a story from the old days. Show the right respect and curiosity.',
  focalWordIds: ['w_tadhakkara', 'w_history', 'w_zaman', 'w_remember', 'w_hikma', 'w_wallah', 'w_inshallah'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'يا ولدي، أنتم ما تعرفون كيف كانت الحياة. زمان، الإنسان يمشي على رجليه من بلد لبلد.', translation: 'My son, you all don\'t know what life was like. In the old days, a man would walk on foot from town to town.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Respond with genuine interest and respect.', options: [
      { text: 'والله يا جدّي، هذا شي ما نتصوّره اليوم. كيف تحمّلتم؟', translation: 'By God, grandfather, that\'s something we can\'t imagine today. How did you endure it?', nextStepId: 's3', correct: true, feedback: 'Perfect — يا جدّي and the follow-up question shows respectful engagement.' },
      { text: 'آه، أعرف. قرأت عن ذلك في المدرسة.', translation: 'Ah, I know. I read about that in school.', nextStepId: 's3', correct: false, feedback: 'You\'re deflecting to your own knowledge instead of honouring his lived experience.' },
      { text: 'نعم، ذلك كان في زمن ما قبل التطور.', translation: 'Yes, that was in the pre-development era.', nextStepId: 's3', correct: false, feedback: 'Too clinical and detached — your grandfather is sharing his soul, not a history lecture.' },
      { text: 'سبحان الله يا جدّي، حدّثني أكثر.', translation: 'Glory to God, grandfather, tell me more.', nextStepId: 's3', correct: true, feedback: 'سبحان الله is a natural reverent response here, and asking for more is exactly right.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'الصبر يا ولدي. كانت الحياة صعبة، لكن كانت فيها بركة ما نشوفها اليوم.', translation: 'Patience, my son. Life was hard, but it had a blessing we don\'t see today.', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Ask about that blessing without sounding dismissive of the present.', options: [
      { text: 'إيش تقصد بالبركة يا جدّي؟ وضّح لي.', translation: 'What do you mean by blessing, grandfather? Explain it to me.', nextStepId: 's5', correct: true, feedback: 'Direct but respectful — وضّح لي invites without pressing.' },
      { text: 'بس الحياة اليوم أحسن بكثير يا جدّي.', translation: 'But life today is much better, grandfather.', nextStepId: 's5', correct: false, feedback: 'You\'re contradicting your grandfather mid-story. Wrong moment — listen first.' },
      { text: 'يمكن البركة في البساطة والقناعة؟', translation: 'Maybe the blessing is in simplicity and contentment?', nextStepId: 's5', correct: true, feedback: 'Thoughtful — you\'re offering a reflection, not cutting him off.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'على بال يا ولدي — البركة في أننا كنّا نعرف قيمة الشي لما نأخذه بتعب.', translation: 'Exactly, my son — the blessing was that we knew the value of something when we earned it through hardship.', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Draw a connection between his wisdom and your life today.', options: [
      { text: 'والله يا جدّي، هذي الحكمة أحتاجها في حياتي كل يوم.', translation: 'By God, grandfather, I need this wisdom in my life every day.', nextStepId: 's7', correct: true, feedback: 'Beautifully connects his wisdom to your present — this is what he wants to hear.' },
      { text: 'نعم، الاقتصاديون يسمّون هذا \'نظرية القيمة\'.', translation: 'Yes, economists call this the \'theory of value\'.', nextStepId: 's7', correct: false, feedback: 'You just turned his wisdom into an academic footnote. Wrong register entirely.' },
      { text: 'شكراً يا جدّي على الكلام الحلو.', translation: 'Thank you grandfather for the kind words.', nextStepId: 's7', correct: false, feedback: 'Too dismissive — \'kind words\' undersells his lived testimony.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'إن شاء الله تنتفع يا ولدي. كلام الكبار ما يضيع — خزّنه في قلبك.', translation: 'God willing, may you benefit, my son. The words of elders don\'t go to waste — store them in your heart.', end: true },
  ],
  completionMessage: 'You showed the right balance of deference, curiosity and genuine engagement. الله يحفظه!',
},

{
  id: 'saudi_convo_p10_career_doubts',
  phase: 10,
  title: 'Career Doubts',
  description: 'A late-night conversation with a close friend about whether you\'re on the right path.',
  focalWordIds: ['w_fakkara', 'w_fikra', 'w_job', 'w_doubt', 'w_nafs', 'w_wallah', 'w_yaani', 'w_khalas'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'أنت زين؟ شايفك مو بنفسك الليلة.', translation: 'Are you okay? I can see you\'re not yourself tonight.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Open up honestly to your close friend.', options: [
      { text: 'والله يا عمي، ما أعرف إذا الشغل الي فيه هو اللي أبيه أصلاً.', translation: 'By God, man, I don\'t know if the job I\'m in is what I actually want.', nextStepId: 's3', correct: true, feedback: 'Honest and natural — والله يا عمي is the right opener for a vulnerable admission.' },
      { text: 'لا، أنا بخير تماماً. شكراً.', translation: 'No, I\'m completely fine. Thanks.', nextStepId: 's3', correct: false, feedback: 'You\'re shutting your friend out when he\'s checking on you. Wrong move.' },
      { text: 'أعاني من بعض التساؤلات المهنية.', translation: 'I\'m experiencing some professional questioning.', nextStepId: 's3', correct: false, feedback: 'Too formal — this is a friend, not your therapist\'s intake form.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'يعني إيش؟ وضّح لي — إيش الي ما عاجبك؟', translation: 'Meaning what? Be clear with me — what is it that you don\'t like?', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Explain the deeper feeling.', options: [
      { text: 'ما يهمّني الراتب ولا المنصب — أبي أحس إن شغلي بيفرّق.', translation: 'The salary and title don\'t matter to me — I want to feel my work makes a difference.', nextStepId: 's5', correct: true, feedback: 'Excellent — ما يهمّني is used perfectly here, showing what really counts.' },
      { text: 'الراتب ضعيف والبيئة سيئة.', translation: 'The salary is weak and the environment is bad.', nextStepId: 's5', correct: false, feedback: 'Legitimate concerns, but too shallow for a deep existential conversation — you\'re describing symptoms, not the wound.' },
      { text: 'أشعر أن هذه المسيرة المهنية لا تتوافق مع قيمي.', translation: 'I feel this career path doesn\'t align with my values.', nextStepId: 's5', correct: false, feedback: 'MSA in a late-night friend chat — the register is off. Too stiff for this moment.' },
      { text: 'خلاص يعني — كل يوم أصحى وما عندي سبب أروح.', translation: 'That\'s just it — every day I wake up with no reason to go.', nextStepId: 's5', correct: true, feedback: 'خلاص يعني captures the resignation perfectly — raw and real.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'ابن الواوي، هذا الكلام مهم. الواحد لازم يعيش بقلب مرتاح.', translation: 'Man, this is important. A person has to live with a settled heart.', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Acknowledge his point but voice your fear of change.', options: [
      { text: 'صح، بس الخوف يا عمي — العيلة، الفلوس، المسؤوليات.', translation: 'True, but the fear, man — family, money, responsibilities.', nextStepId: 's7', correct: true, feedback: 'Real and vulnerable — names the actual obstacles without self-pity.' },
      { text: 'نعم لكنّ التغيير المهني ينطوي على مخاطر كبيرة.', translation: 'Yes but professional change entails significant risks.', nextStepId: 's7', correct: false, feedback: 'Too corporate — you\'re talking to your best friend, not writing a risk assessment.' },
      { text: 'أوافقك الرأي. سأستقيل غداً.', translation: 'I agree with you. I\'ll resign tomorrow.', nextStepId: 's7', correct: false, feedback: 'Overcorrection — jumping to a snap decision undermines the authenticity of the conversation.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'ما يهمّك — فكّر بهدوء، وأنا معك مهما قررت. الحياة مو سباق.', translation: 'Don\'t worry — think calmly, and I\'m with you whatever you decide. Life isn\'t a race.', end: true },
  ],
  completionMessage: 'You opened up with the right tone and vocabulary. ما يهمّك — that\'s real friendship.',
},

{
  id: 'saudi_convo_p10_apology_serious',
  phase: 10,
  title: 'A Serious Apology',
  description: 'You wronged a close friend seriously. This is the conversation where you own it fully.',
  focalWordIds: ['w_ghafara', 'w_maghfira', 'w_haqq', 'w_wallah', 'w_qalb', 'w_nafs', 'w_friend'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'تكلّم. جيت تقول إيش؟', translation: 'Speak. What did you come to say?', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Open your apology. This is a serious moment — own it fully.', options: [
      { text: 'جيت أعتذر. والله العظيم ما قصّدت أأذيك، وأعرف إن كلامي كان غلط.', translation: 'I came to apologise. I swear to God I didn\'t mean to hurt you, and I know what I said was wrong.', nextStepId: 's3', correct: true, feedback: 'والله العظيم carries real weight here — it signals sincerity, not just words.' },
      { text: 'آسف إذا شعرت بشيء.', translation: 'Sorry if you felt something.', nextStepId: 's3', correct: false, feedback: 'A conditional non-apology. \'If you felt something\' puts the blame on his sensitivity, not your actions.' },
      { text: 'أعتذر رسمياً عمّا صدر مني.', translation: 'I formally apologise for what came from me.', nextStepId: 's3', correct: false, feedback: 'Too formal and detached — رسمياً signals bureaucracy, not genuine remorse.' },
      { text: 'أنا آسف. ما أبي أخسرك.', translation: 'I\'m sorry. I don\'t want to lose you.', nextStepId: 's3', correct: true, feedback: 'Simple and direct — ما أبي أخسرك is vulnerable and real.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'كلمتني أمام الكل بطريقة ما توصف. تحسب هذا ينحل بكلمة؟', translation: 'You spoke to me in front of everyone in an indescribable way. You think this resolves with one word?', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'He\'s right to be hurt. Acknowledge the depth of what you did.', options: [
      { text: 'ما أبي أبرّر. اللي سوّيته غلط وما أقبل عذر لنفسي.', translation: 'I don\'t want to justify it. What I did was wrong and I won\'t excuse myself.', nextStepId: 's5', correct: true, feedback: 'This is the gold standard — no justifications, full accountability.' },
      { text: 'كنت متوتراً في ذلك اليوم. أملي تفهم.', translation: 'I was stressed that day. I hope you understand.', nextStepId: 's5', correct: false, feedback: 'You\'re explaining, which is a subtle form of justification. He doesn\'t owe you understanding right now.' },
      { text: 'نعم، الاعتراف بالخطأ فضيلة.', translation: 'Yes, acknowledging a mistake is a virtue.', nextStepId: 's5', correct: false, feedback: 'You just quoted a proverb instead of apologising. Wrong move.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'يعني إيش تبي مني الحين؟', translation: 'So what do you want from me now?', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Don\'t demand forgiveness. Ask humbly.', options: [
      { text: 'ما أطلب منك شي — بس أبيك تعرف إني آسف من قلبي.', translation: 'I\'m not asking you for anything — I just want you to know I\'m sorry from my heart.', nextStepId: 's7', correct: true, feedback: 'Perfect — you\'re not transacting forgiveness, you\'re offering genuine remorse.' },
      { text: 'أبيك تسامحني. نحن أصدقاء.', translation: 'I want you to forgive me. We\'re friends.', nextStepId: 's7', correct: false, feedback: 'Invoking the friendship as leverage is manipulative. He gets to decide the pace of forgiveness.' },
      { text: 'أريد أن تمنحني فرصة ثانية.', translation: 'I want you to give me a second chance.', nextStepId: 's7', correct: false, feedback: 'Too transactional and formal — you\'re presenting terms, not making a human appeal.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'الله يغفر لنا جميعاً. محتاج وقت — بس أنا ما نسيت إنك صاحبي.', translation: 'May God forgive us all. I need time — but I haven\'t forgotten you\'re my friend.', end: true },
  ],
  completionMessage: 'You navigated a difficult apology with the sincerity and humility it deserved. الله يغفر ويصلح.',
},

{
  id: 'saudi_convo_p10_intellectual_debate',
  phase: 10,
  title: 'Intellectual Debate',
  description: 'A sharp debate about tradition versus modernity with an educated peer.',
  focalWordIds: ['w_opinion', 'w_debate', 'w_culture', 'w_think', 'w_because', 'w_ikhtalafa', 'w_although', 'w_society'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'التراث في رأيي عبء أكثر من كونه قيمة — الأمم التي تقدّمت تخلّت عنه إلى حدٍّ كبير.', translation: 'Heritage in my view is more of a burden than a value — the nations that advanced largely abandoned it.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Challenge this view with substance and confidence.', options: [
      { text: 'هذا الكلام فيه مغالطة — التقدم الياباني والكوري بُني على هوية راسخة، مو على محو الهوية.', translation: 'This argument contains a fallacy — Japanese and Korean advancement was built on a firm identity, not the erasure of identity.', nextStepId: 's3', correct: true, feedback: 'Strong counter with a concrete example — exactly the right move in an intellectual debate.' },
      { text: 'لا أوافقك الرأي. التراث مهم.', translation: 'I disagree with you. Heritage is important.', nextStepId: 's3', correct: false, feedback: 'Too flat — you\'re asserting without arguing. In a debate, you need to show your reasoning.' },
      { text: 'والله ما تكلمت في هذا الموضوع من قبل.', translation: 'By God I haven\'t spoken about this topic before.', nextStepId: 's3', correct: false, feedback: 'Deflection is not debate. Engage the argument.' },
      { text: 'أنت تخلط بين التراث والتخلف — ليسا مترادفَين.', translation: 'You\'re confusing heritage with backwardness — they\'re not synonyms.', nextStepId: 's3', correct: true, feedback: 'Sharp and clear — identifies the conceptual error in his framing.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'نقطة وجيهة. لكن ألا ترى أن كثيراً من التقاليد تُقيّد حرية الفرد؟', translation: 'A valid point. But don\'t you see that many traditions constrain individual freedom?', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Acknowledge the valid part while pushing back on the overgeneralization.', options: [
      { text: 'صح في بعض الحالات — بس الحل تصفية التراث مو هدمه. ابن الواوي مو كل تراث مقيّد.', translation: 'True in some cases — but the solution is refining heritage, not demolishing it. Come on, not all heritage is restrictive.', nextStepId: 's5', correct: true, feedback: 'Code-switching and the nuanced concession-then-push is perfect debating.' },
      { text: 'نعم، التراث يقيّد الحرية الفردية دائماً.', translation: 'Yes, heritage always constrains individual freedom.', nextStepId: 's5', correct: false, feedback: 'You just agreed with him completely — no point debating if you concede everything.' },
      { text: 'الحرية الفردية مفهوم غربي لا ينطبق على مجتمعاتنا.', translation: 'Individual freedom is a Western concept that doesn\'t apply to our societies.', nextStepId: 's5', correct: false, feedback: 'A dismissive non-argument — you\'re shutting down the discussion rather than engaging it.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'التصفية — من يحدّدها؟ من يملك سلطة تقرير ما يبقى وما يُلغى؟', translation: 'Refinement — who defines it? Who holds the authority to decide what stays and what is cancelled?', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'This is the sharpest question in the debate. Engage it seriously.', options: [
      { text: 'سؤال ذكي. ربما المجتمع نفسه عبر نقاش مستمر — ما في جهة واحدة تملك هذا الحق.', translation: 'Sharp question. Perhaps society itself through ongoing debate — no single party holds this right.', nextStepId: 's7', correct: true, feedback: 'Excellent — you acknowledge the weight of the question and give a thoughtful democratic answer.' },
      { text: 'العلماء والمختصون هم من يقرّرون.', translation: 'Scholars and specialists are the ones who decide.', nextStepId: 's7', correct: false, feedback: 'An elitist answer that ignores the power-dynamics problem he just raised.' },
      { text: 'هذا سؤال فلسفي ما له جواب.', translation: 'That\'s a philosophical question with no answer.', nextStepId: 's7', correct: false, feedback: 'Conceding the debate by declaring it unanswerable. Don\'t give up.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'إذن نتّفق أن القضية أعمق من ثنائية تراث ومعاصرة. الحوار نفسه هو الإجابة.', translation: 'Then we agree that the issue is deeper than the binary of heritage versus modernity. The dialogue itself is the answer.', end: true },
  ],
  completionMessage: 'A masterful intellectual exchange. You argued with rigour, acknowledged valid points, and kept the dialogue alive.',
},

{
  id: 'saudi_convo_p10_family_disagreement',
  phase: 10,
  title: 'Family Disagreement',
  description: 'A tense disagreement with your mother about a major life decision.',
  focalWordIds: ['w_mother', 'w_haqq', 'w_think', 'w_because', 'w_wallah', 'w_inshallah', 'w_qalb'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'ما أقدر أصدّق إنك تفكر بهذا — إيش رأي أبوك؟', translation: 'I can\'t believe you\'re thinking about this — what\'s your father\'s opinion?', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Respond calmly but stand your ground.', options: [
      { text: 'يا أمي، أبوي عارف وهو معي. بس هذا قراري أنا في النهاية.', translation: 'Mama, dad knows and he\'s with me. But this is ultimately my decision.', nextStepId: 's3', correct: true, feedback: 'Good — you\'re reassuring her without surrendering your autonomy.' },
      { text: 'هذا لا يخصّ أبوي.', translation: 'This doesn\'t concern dad.', nextStepId: 's3', correct: false, feedback: 'Too sharp — you\'re cutting the family out instead of bringing them in.' },
      { text: 'والله يا أمي أنا خايف أذيّ مشاعرك، بس لازم أكون صريح.', translation: 'By God, mama, I\'m scared to hurt your feelings, but I need to be honest.', nextStepId: 's3', correct: true, feedback: 'Vulnerability with honesty — the right combo when disagreeing with a parent.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'يعني قرارك أهم من راحة البال؟ من صغيرك حتى الكبر — من تعبت عليك؟', translation: 'So your decision matters more than peace of mind? From childhood to adulthood — who put in the effort for you?', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'She\'s invoking her sacrifice. Honour it without giving in to guilt.', options: [
      { text: 'والله ما أنكر تعبك أبداً يا أمي — وهذا اللي يخلّيني أبي أكون صادق معك.', translation: 'By God, I\'d never deny your effort, mama — and that\'s exactly what makes me want to be honest with you.', nextStepId: 's5', correct: true, feedback: 'Brilliant reframe — her sacrifice becomes the reason for honesty, not submission.' },
      { text: 'أنا ممتنّ لكل شيء، لكن هذا لا يعني أنّ حياتي ملكك.', translation: 'I\'m grateful for everything, but that doesn\'t mean my life belongs to you.', nextStepId: 's5', correct: false, feedback: 'True, but brutally blunt with a mother. The sentiment is right but the delivery cuts too deep.' },
      { text: 'معك حق يا أمي. سأتراجع عن قراري.', translation: 'You\'re right, mama. I\'ll reverse my decision.', nextStepId: 's5', correct: false, feedback: 'You\'re capitulating out of guilt, not conviction. That helps no one.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'صادق؟ الصدق إنك تسمع كلام أمك وتتريّث.', translation: 'Honest? Honesty means you listen to your mother and take your time.', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Find the middle ground she needs to hear.', options: [
      { text: 'زين يا أمي — والله ما أبي أتسرّع. أعطيني أسبوع أفكّر وبعدين نتكلم سوا.', translation: 'Okay, mama — by God I don\'t want to rush. Give me a week to think and then we\'ll talk together.', nextStepId: 's7', correct: true, feedback: 'خلاص يعني-style resolution — not surrender, but a genuine pause that respects her concern.' },
      { text: 'حسناً، سأفكّر في الأمر.', translation: 'Fine, I\'ll think about it.', nextStepId: 's7', correct: false, feedback: 'Too flat and dismissive — she\'ll hear this as brushing her off.' },
      { text: 'ما يهمّك يا أمي، كل شي بيكون تمام.', translation: 'Don\'t worry, mama, everything will be fine.', nextStepId: 's7', correct: false, feedback: 'You\'re closing the conversation rather than opening a real dialogue.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'الله يهديك يا ولدي. أنا ما أريد إلا خيرك، وأنت تعرف هذا.', translation: 'May God guide you, my child. I want nothing but the best for you, and you know that.', end: true },
  ],
  completionMessage: 'You navigated a charged family disagreement with love and clarity. الله يحفظ الأمهات.',
},

{
  id: 'saudi_convo_p10_break_bad_news',
  phase: 10,
  title: 'Breaking Bad News',
  description: 'You must deliver painful news to a close friend about someone they love.',
  focalWordIds: ['w_khabar', 'w_news', 'w_qalb', 'w_mawt', 'w_wallah', 'w_inshallah', 'w_sabab'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'إيش فيك؟ وجهك ما يشبه وجهك.', translation: 'What\'s wrong with you? Your face doesn\'t look like yourself.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Prepare him gently before sharing the news.', options: [
      { text: 'اقعد معي يا عمي. عندي خبر ما سهل.', translation: 'Sit with me, man. I have some difficult news.', nextStepId: 's3', correct: true, feedback: 'Gentle preparation before delivery — the right way to break bad news.' },
      { text: 'أخوك في المستشفى.', translation: 'Your brother is in the hospital.', nextStepId: 's3', correct: false, feedback: 'Dropping the news cold without any preparation. Too harsh.' },
      { text: 'لا شيء. بس أنا تعبان شوي.', translation: 'Nothing. I\'m just a little tired.', nextStepId: 's3', correct: false, feedback: 'Hiding the news doesn\'t help anyone — you came to tell him, so tell him with care.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'إيش؟ قوللي — خوّفتني.', translation: 'What? Tell me — you scared me.', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Deliver the news with compassion.', options: [
      { text: 'والله يا عمي، الله يصبّرك — عمّك ابو ناصر توفّي الفجر اليوم.', translation: 'By God, man, may God grant you patience — your uncle Abu Nasser passed away this morning at dawn.', nextStepId: 's5', correct: true, feedback: 'الله يصبّرك before the news is the traditional and deeply human Saudi way to deliver this.' },
      { text: 'للأسف، عمّك فارق الحياة اليوم.', translation: 'Unfortunately, your uncle departed life today.', nextStepId: 's5', correct: false, feedback: 'The MSA framing feels clinical in this intimate moment. Warmth is needed.' },
      { text: 'عمّك توفّي — اتصلت أمك قبل شوي.', translation: 'Your uncle passed away — your mother called a little while ago.', nextStepId: 's5', correct: false, feedback: 'No buffer, no دعاء — dropping the news like a fact, not news about someone he loves.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'إنّا لله... — والله ما صدّقت. متى؟', translation: 'Surely we belong to God... — by God I can\'t believe it. When?', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Answer gently and stay present with him.', options: [
      { text: 'الفجر. كان نايم — الله يرحمه، ما تعذّب.', translation: 'At dawn. He was sleeping — may God have mercy on him, he didn\'t suffer.', nextStepId: 's7', correct: true, feedback: 'The detail about not suffering is a gift of comfort. الله يرحمه is essential.' },
      { text: 'قبل ثلاث ساعات تقريباً.', translation: 'About three hours ago.', nextStepId: 's7', correct: false, feedback: 'Technically correct but emotionally empty — no dua, no comfort.' },
      { text: 'ما أعرف بالضبط.', translation: 'I don\'t know exactly.', nextStepId: 's7', correct: false, feedback: 'Unhelpful and distancing when your friend needs presence, not vagueness.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'الله يرحمه ويغفر له. شكراً إنك جيت تقوللي بنفسك — هذا ما نسّيته.', translation: 'May God have mercy on him and forgive him. Thank you for coming to tell me yourself — I won\'t forget this.', end: true },
  ],
  completionMessage: 'You delivered painful news with the care and presence it deserves. الله يرحم الجميع.',
},

{
  id: 'saudi_convo_p10_persuade_father',
  phase: 10,
  title: 'Persuading Your Father',
  description: 'You want your father\'s blessing for a bold career move. Navigate his concerns with respect.',
  focalWordIds: ['w_father', 'w_think', 'w_fikra', 'w_haqq', 'w_wallah', 'w_inshallah', 'w_because', 'w_sabab'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'تقدر تقنعني بأي حجة إنك تترك الوظيفة الحكومية؟ الأمان يا ولد.', translation: 'Can you convince me with any argument that you should leave the government job? Security, son.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Open your case with respect and substance.', options: [
      { text: 'يا أبوي، الأمان المادي مهم — بس الأمان النفسي أهم. وأنا هناك ما عندي الثاني.', translation: 'Father, financial security matters — but psychological security matters more. And I don\'t have the second one there.', nextStepId: 's3', correct: true, feedback: 'A structured, respectful argument that honours his concern while introducing your own.' },
      { text: 'المشاريع الخاصة أفضل بكثير من الحكومة.', translation: 'Private ventures are much better than government.', nextStepId: 's3', correct: false, feedback: 'Too blunt a counter to a traditional father — you need to earn the right to say that, not open with it.' },
      { text: 'أبوي، الزمن تغيّر — الوظيفة الحكومية ما هي ضمان اليوم.', translation: 'Father, times have changed — government employment is no longer a guarantee today.', nextStepId: 's3', correct: true, feedback: 'Smart — you use a factual framing he can\'t dismiss, not just your personal preference.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'الأمان النفسي؟ الجوع ما يرحم يا ولد — سأل الناس اللي جرّبوا.', translation: 'Psychological security? Hunger shows no mercy, son — ask the people who\'ve tried it.', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Show him you\'ve done the groundwork, not just dreaming.', options: [
      { text: 'أنا ما أتكلم من فراغ يا أبوي — عندي عملاء محتملين وخطة وتدفق نقدي يكفي ستة أشهر.', translation: 'I\'m not speaking from thin air, father — I have potential clients, a plan, and cash flow for six months.', nextStepId: 's5', correct: true, feedback: 'Concrete data kills vague fear — this is exactly what a cautious father needs to hear.' },
      { text: 'أنا واثق بنفسي يا أبوي. الله يفتح.', translation: 'I\'m confident in myself, father. God will provide.', nextStepId: 's5', correct: false, feedback: 'Faith without preparation isn\'t reassuring — it confirms his worst fear that you\'re being reckless.' },
      { text: 'سأقبل المخاطرة لأن الفرصة لن تعود.', translation: 'I\'ll accept the risk because the opportunity won\'t return.', nextStepId: 's5', correct: false, feedback: 'FOMO framing won\'t persuade a father — he needs methodical reassurance, not urgency.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'ستة أشهر؟ وبعدين إيش إذا ما نجح الشغل؟', translation: 'Six months? And then what if the business doesn\'t succeed?', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Address the failure scenario honestly.', options: [
      { text: 'إذا فشلت — والله ما هو الخيار الأسوأ في الدنيا — أرجع للسوق وعندي خبرة أكثر.', translation: 'If I fail — by God it\'s not the worst thing in the world — I return to the market with more experience.', nextStepId: 's7', correct: true, feedback: 'Naming failure without fear is mature and reassuring — it shows you\'ve thought this through.' },
      { text: 'مو راح أفشل يا أبوي.', translation: 'I\'m not going to fail, father.', nextStepId: 's7', correct: false, feedback: 'Overconfidence. No father trusts this — every entrepreneur who failed said the same thing.' },
      { text: 'إن شاء الله ما يحصل هذا.', translation: 'God willing that won\'t happen.', nextStepId: 's7', correct: false, feedback: 'Deflecting to faith without a real plan doesn\'t address his concern.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'والله الله يوفّقك يا ولدي. بس وعدني — ما تتفاجأ الناس، واللي تسوّيه اعمله بطريقة صحيحة.', translation: 'By God, may God grant you success, my son. But promise me — don\'t surprise people, and whatever you do, do it the right way.', end: true },
  ],
  completionMessage: 'You earned your father\'s blessing through preparation, honesty, and respect. الله يوفّقك!',
},

{
  id: 'saudi_convo_p10_decline_marriage_proposal',
  phase: 10,
  title: 'Declining a Marriage Proposal',
  description: 'You must decline a marriage proposal gracefully while preserving everyone\'s dignity.',
  focalWordIds: ['w_haqq', 'w_qalb', 'w_think', 'w_wallah', 'w_inshallah', 'w_because', 'w_nafs'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'العيلة كلها متحمّسة — والله ما نقدر نتخيّل أحسن منك. إيش ردّك؟', translation: 'The whole family is excited — by God we can\'t imagine anyone better than you. What\'s your answer?', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Respond with warmth before declining.', options: [
      { text: 'والله يشرّفني الكلام هذا — وأقدّر ثقتكم. بس لازم أكون صريح معكم.', translation: 'By God these words honour me — and I value your trust. But I must be honest with you.', nextStepId: 's3', correct: true, feedback: 'Perfect opener — gratitude before honesty preserves everyone\'s dignity.' },
      { text: 'لا. شكراً على العرض.', translation: 'No. Thank you for the offer.', nextStepId: 's3', correct: false, feedback: 'Too abrupt — this is a family matter that deserves warmth and care, not a business rejection.' },
      { text: 'سأحتاج إلى مزيد من الوقت للتفكير.', translation: 'I\'ll need more time to think.', nextStepId: 's3', correct: false, feedback: 'If you already know your answer, stalling gives false hope — that\'s unkind.' },
      { text: 'يا شيخ، شرفتوني — بس قلبي ما فيه استعداد الحين.', translation: 'Truly you\'ve honoured me — but my heart isn\'t ready right now.', nextStepId: 's3', correct: true, feedback: 'Warm and honest — leading with the heart is respected in this kind of conversation.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'كلام صريح نقدّره. إيش المانع إذا جاز السؤال؟', translation: 'We appreciate the honesty. What\'s the obstacle, if we may ask?', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Explain without shaming anyone.', options: [
      { text: 'ما فيه مانع من جهتكم أبداً — الأمر عندي أنا. ما أقدر أدخل في ارتباط وقلبي مو معه.', translation: 'There\'s no obstacle from your side at all — the matter is with me. I can\'t enter a commitment when my heart isn\'t in it.', nextStepId: 's5', correct: true, feedback: 'Taking full ownership protects the other party\'s honour completely.' },
      { text: 'الفتاة ما تناسبني.', translation: 'The girl doesn\'t suit me.', nextStepId: 's5', correct: false, feedback: 'Too direct about the other person — this shames them. Keep it about yourself.' },
      { text: 'ظروف الحياة صعبة الآن ومالياً لست مستعداً.', translation: 'Life circumstances are difficult now and financially I\'m not ready.', nextStepId: 's5', correct: false, feedback: 'Hiding behind a practical excuse when the real answer is emotional — not fully honest, and leaves the door open.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'نفهم. الإنسان لازم يكون مقتنع — والله اللي يكتبه الله يجي.', translation: 'We understand. A person must be convinced — by God what God writes will come.', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Close with warmth and a dua.', options: [
      { text: 'الله يكرمكم ويرزقها بأحسن مني — والله ما أشكّ في قيمتها.', translation: 'May God honour you and bless her with better than me — by God I don\'t doubt her worth.', nextStepId: 's7', correct: true, feedback: 'A generous closing dua that lifts everyone. This is the mark of character.' },
      { text: 'شكراً على تفهّمكم.', translation: 'Thank you for your understanding.', nextStepId: 's7', correct: false, feedback: 'Too clinical for a family moment — a warm دعاء is expected here.' },
      { text: 'إن شاء الله كل شيء سيسير على ما يرام.', translation: 'God willing everything will go well.', nextStepId: 's7', correct: false, feedback: 'A generic placeholder — show genuine care for the other family\'s wellbeing.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'الله يعوّضها خير. ولا في حالك — إنت كذلك تستاهل اللي يسعدك.', translation: 'May God compensate her with goodness. And be well — you too deserve what makes you happy.', end: true },
  ],
  completionMessage: 'You declined with grace, warmth, and full respect for everyone\'s dignity. ما شاء الله.',
},

{
  id: 'saudi_convo_p10_consult_imam',
  phase: 10,
  title: 'Consulting the Imam',
  description: 'You seek religious and personal guidance from the mosque imam on a difficult moral question.',
  focalWordIds: ['w_iimaan', 'w_haqq', 'w_hikma', 'w_wallah', 'w_inshallah', 'w_hada', 'w_ghafara'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'تفضّل يا ولدي — ما يجيب الإنسان عند الشيخ إلا شي يثقّل القلب.', translation: 'Come in, my son — nothing brings a person to the sheikh except something that weighs on the heart.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Open with respect and a brief framing of your question.', options: [
      { text: 'صحيح يا شيخنا — عندي موضوع حيّرني وخفت أقرر بدون ما أستشير.', translation: 'True, our sheikh — I have a matter that confused me and I was afraid to decide without consulting.', nextStepId: 's3', correct: true, feedback: 'Respectful and humble — exactly the right register for consulting a religious authority.' },
      { text: 'عندي سؤال شرعي.', translation: 'I have a legal question.', nextStepId: 's3', correct: false, feedback: 'Too clinical and transactional. The imam opened warmly — match his register.' },
      { text: 'أريد معرفة الحكم الشرعي في مسألة معيّنة.', translation: 'I want to know the religious ruling in a specific matter.', nextStepId: 's3', correct: false, feedback: 'Formal MSA framing when the imam used a warm, pastoral tone. Read the room.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'حيّاك الله. تكلّم بلا خجل — ما في سؤال يُعاب على من أراد الحق.', translation: 'God bless you. Speak without shame — there is no question that reproaches one who seeks the truth.', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Describe your moral dilemma.', options: [
      { text: 'يا شيخنا، عندي صاحب يغشّ في شغله وعندي معلومة تضرّه إذا كشفتها — ما أدري هل أقول ولا أسكت.', translation: 'Our sheikh, I have a friend who cheats in his work and I have information that would harm him if I exposed it — I don\'t know whether to speak or stay silent.', nextStepId: 's5', correct: true, feedback: 'Clear, specific dilemma that sets up a rich dialogue.' },
      { text: 'سؤالي عن الأمانة في العمل.', translation: 'My question is about integrity at work.', nextStepId: 's5', correct: false, feedback: 'Too abstract — the imam needs the real situation to give real guidance.' },
      { text: 'أريد أن أعرف إذا كان عليّ واجب تجاه صديق يرتكب خطأ.', translation: 'I want to know if I have a duty toward a friend who commits a mistake.', nextStepId: 's5', correct: false, feedback: 'Too distanced — you\'re describing it from a textbook angle rather than living it.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'هذا ميزان دقيق — النصيحة واجبة، لكن طريقتها أهم من قرارها. نصحته أنت أولاً؟', translation: 'This is a delicate balance — advice is obligatory, but its method matters more than the decision. Have you advised him first?', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Answer honestly.', options: [
      { text: 'لا يا شيخنا — وهذا اللي يؤلمني. كنت أتجنّب الموضوع وما أعرف ليش.', translation: 'No, our sheikh — and this is what pains me. I was avoiding the matter and I don\'t know why.', nextStepId: 's7', correct: true, feedback: 'Honest self-reflection — showing the imam you\'re part of the equation too.' },
      { text: 'لا، لأنّ الوضع معقّد جداً.', translation: 'No, because the situation is very complicated.', nextStepId: 's7', correct: false, feedback: 'Excuse-making rather than honesty. The imam will see through it.' },
      { text: 'نعم، نصحته لكنّه لم يسمع.', translation: 'Yes, I advised him but he didn\'t listen.', nextStepId: 's7', correct: false, feedback: 'Don\'t fabricate — if you haven\'t actually advised him, saying you have closes the dialogue.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'إذن ابدأ من هناك — بالحكمة واللين. ما يهمّك ما سيكون ردّه — أنت مسؤول عن الكلمة اللي تقولها، مو عن قلبه هو.', translation: 'Then start there — with wisdom and gentleness. Don\'t worry about what his response will be — you\'re responsible for the word you speak, not for his heart.', end: true },
  ],
  completionMessage: 'You engaged a religious consultation with the right humility and honesty. الله يهدينا جميعاً.',
},

{
  id: 'saudi_convo_p10_eulogy_remembrance',
  phase: 10,
  title: 'Eulogy and Remembrance',
  description: 'Sharing memories of a passed loved one at a gathering of family.',
  focalWordIds: ['w_tadhakkara', 'w_remember', 'w_qalb', 'w_mawt', 'w_hayaa', 'w_wallah', 'w_ghafara'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'الله يرحمه. كان رجل ما فيه مثيل — كل من عرفه بكى عليه.', translation: 'May God have mercy on him. He was a man with no equal — everyone who knew him wept for him.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Share a genuine memory of the deceased.', options: [
      { text: 'والله، أذكر لما كنت صغير يجلسني جنبه ويحكيلي قصص الأجداد — ما نسيت ولا كلمة.', translation: 'By God, I remember when I was young he would sit me beside him and tell me stories of the ancestors — I haven\'t forgotten a single word.', nextStepId: 's3', correct: true, feedback: 'Specific and vivid — a real memory is more powerful than any general praise.' },
      { text: 'كان إنساناً طيباً ومحبوباً من الجميع.', translation: 'He was a kind person loved by everyone.', nextStepId: 's3', correct: false, feedback: 'Generic and hollow — this could describe anyone. Share something real.' },
      { text: 'نعم، كان شخصاً ذا قيم رفيعة.', translation: 'Yes, he was a person of high values.', nextStepId: 's3', correct: false, feedback: 'MSA eulogy-speak that creates distance rather than closeness. Too formal for a family gathering.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'على بال الأيام اللي كنّا نجتمع فيها كلنا — يمشي بيننا بهدوء ويسوّي الأمور.', translation: 'Those days when we all gathered are still in my heart — he would move among us quietly and make things right.', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Add to his portrait with another facet of his character.', options: [
      { text: 'ما كان يرفع صوته على أحد — وكانت كلمته تساوي ألف.', translation: 'He never raised his voice at anyone — yet his word was worth a thousand.', nextStepId: 's5', correct: true, feedback: 'Poetic and specific — captures quiet authority beautifully.' },
      { text: 'كان يحبّ الأسرة كثيراً.', translation: 'He loved the family a lot.', nextStepId: 's5', correct: false, feedback: 'Too generic — add texture to the portrait.' },
      { text: 'لقد قدّم تضحيات جسيمة من أجل العائلة.', translation: 'He made great sacrifices for the family.', nextStepId: 's5', correct: false, feedback: 'Formal and vague — the gathering needs specifics that trigger real emotion.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'صحيح والله. آخر مرة شفته — قالي: \'اعتنِ بإخوانك.\' ما عرفت إنها الوداع.', translation: 'So true, by God. The last time I saw him — he told me: \'Take care of your siblings.\' I didn\'t know it was goodbye.', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Respond to his grief with presence and meaning.', options: [
      { text: 'والله يا عمي — هذي وصيّة، مو وداع. وأنت لازم تمشي فيها.', translation: 'By God, man — that\'s a bequest, not a goodbye. And you have to walk in it.', nextStepId: 's7', correct: true, feedback: 'Transforms grief into purpose — this is the highest form of comfort.' },
      { text: 'إنّا لله وإنّا إليه راجعون.', translation: 'Surely to God we belong and to Him we return.', nextStepId: 's7', correct: false, feedback: 'A sincere phrase but used here as a conversation-stopper rather than genuine engagement.' },
      { text: 'لا تحزن — الله يرحمه.', translation: 'Don\'t be sad — may God have mercy on him.', nextStepId: 's7', correct: false, feedback: 'Telling someone not to grieve is dismissive, not comforting.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'والله ذكّرتني — الله يرحمه ويجمعنا فيه في الجنة. ما يموت من يُذكر.', translation: 'By God you reminded me — may God have mercy on him and gather us with him in paradise. One who is remembered does not die.', end: true },
  ],
  completionMessage: 'You honoured a life with specific memory and transformed grief into meaning. الله يرحم الجميع.',
},

{
  id: 'saudi_convo_p10_artist_interview',
  phase: 10,
  title: 'Artist Interview',
  description: 'You\'re being interviewed about your artistic work. Navigate questions with depth and authenticity.',
  focalWordIds: ['w_fikra', 'w_fakkara', 'w_culture', 'w_because', 'w_nafs', 'w_wallah', 'w_society'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'شغلك يقول أشياء صعبة بلغة جميلة — من وين تجي الأفكار؟', translation: 'Your work says difficult things in a beautiful language — where do the ideas come from?', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Answer with authenticity, not performance.', options: [
      { text: 'والله — من الحياة نفسها. من المواقف اللي ما تنقال بالكلام العادي.', translation: 'By God — from life itself. From moments that can\'t be said with ordinary words.', nextStepId: 's3', correct: true, feedback: 'Authentic and unpretentious — the best kind of artist answer.' },
      { text: 'أتأثر بالفنانين الكبار الذين درستهم في الجامعة.', translation: 'I\'m influenced by the great artists I studied at university.', nextStepId: 's3', correct: false, feedback: 'Academic deflection — you\'re citing your education instead of revealing yourself.' },
      { text: 'الإلهام يأتي من الله ومن الطبيعة.', translation: 'Inspiration comes from God and from nature.', nextStepId: 's3', correct: false, feedback: 'Too generic — this is the safe answer every artist gives. Go deeper.' },
      { text: 'من الأشياء اللي يخاف الناس يقولونها — أنا بس أقولها بشكل ثاني.', translation: 'From the things people are afraid to say — I just say them a different way.', nextStepId: 's3', correct: true, feedback: 'Bold and specific — this is the kind of answer that makes a great interview.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'بعض الناس يقولون شغلك يكسر تابوهات — إيش رأيك في هذا الوصف؟', translation: 'Some people say your work breaks taboos — what do you think of this description?', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Engage this description thoughtfully.', options: [
      { text: 'ما أبي أكسر شي — أبي أفتح نوافذ. الفرق كبير.', translation: 'I don\'t want to break anything — I want to open windows. The difference is significant.', nextStepId: 's5', correct: true, feedback: 'A beautiful distinction that reframes the narrative — shows depth of thought.' },
      { text: 'نعم، الفن دائماً يكسر التابوهات.', translation: 'Yes, art always breaks taboos.', nextStepId: 's5', correct: false, feedback: 'A cliché answer that says nothing about you specifically.' },
      { text: 'لست مهتماً بما يقوله الناس عن عملي.', translation: 'I\'m not interested in what people say about my work.', nextStepId: 's5', correct: false, feedback: 'The detached artist pose — it\'s a cliché, and closing the question is boring in an interview.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'نوافذ — تعجبني. على بال مَن تفكّر لما تشتغل؟', translation: 'Windows — I like that. Who is on your mind when you work?', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Name your real audience.', options: [
      { text: 'الشخص اللي كنته أنا قبل عشر سنين — اللي ما كان يجد أحداً يعبّر عمّا يحسّ.', translation: 'The person I was ten years ago — the one who couldn\'t find anyone expressing what he felt.', nextStepId: 's7', correct: true, feedback: 'Deeply personal and universal — this is the answer that makes people feel seen.' },
      { text: 'الجيل الشاب المبدع.', translation: 'The young creative generation.', nextStepId: 's7', correct: false, feedback: 'Too broad and marketing-speak — it doesn\'t reveal anything real.' },
      { text: 'الجمهور في المقام الأول.', translation: 'The audience first and foremost.', nextStepId: 's7', correct: false, feedback: 'A non-answer. Every artist says this.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'والله هذا الجواب وحده يساوي مقابلة كاملة. شكراً — الناس محتاجة تسمع هذا.', translation: 'By God, that answer alone is worth a whole interview. Thank you — people need to hear this.', end: true },
  ],
  completionMessage: 'You gave authentic, layered answers that go beyond surface performance. هذا هو الفن الحقيقي.',
},

{
  id: 'saudi_convo_p10_philosophical_chat',
  phase: 10,
  title: 'Philosophical Chat',
  description: 'A deep late-night philosophical exchange about fate, choice, and meaning.',
  focalWordIds: ['w_fakkara', 'w_fikra', 'w_believe', 'w_doubt', 'w_nafs', 'w_wallah', 'w_because', 'w_haqq'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'إذا كل شي مقدّر — ليش نتعب نختار؟', translation: 'If everything is predestined — why do we exhaust ourselves choosing?', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Engage this philosophical question with nuance.', options: [
      { text: 'ربما القدر هو الإطار، والاختيار هو اللوحة اللي تُرسم جوّاه.', translation: 'Perhaps fate is the frame, and choice is the painting drawn within it.', nextStepId: 's3', correct: true, feedback: 'A poetic and philosophically sound metaphor — the right register for this conversation.' },
      { text: 'هذا سؤال ديني وما ينبغي لنا الخوض فيه.', translation: 'This is a religious question and we shouldn\'t delve into it.', nextStepId: 's3', correct: false, feedback: 'Shutting down a sincere philosophical inquiry — wrong move between two thoughtful friends.' },
      { text: 'لأن الله أعطانا العقل لنستخدمه.', translation: 'Because God gave us minds to use.', nextStepId: 's3', correct: false, feedback: 'True but too simple — it doesn\'t actually engage the tension in his question.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'جميل — بس اللوحة نفسها أليست مقدّرة؟ يعني حتى اختياراتك كانت مكتوبة.', translation: 'Beautiful — but isn\'t the painting itself predestined? Meaning even your choices were written.', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Respond to this deeper challenge.', options: [
      { text: 'ابن الواوي — هذا السؤال أرّقني ليالي. بس أنا أشوف إن المسؤولية ما تنفي القدر — الإثنين حقيقيان في آنٍ واحد.', translation: 'Man, this question has kept me up many nights. But I see responsibility doesn\'t negate fate — both are real simultaneously.', nextStepId: 's5', correct: true, feedback: 'ابن الواوي as an opener grounds the lofty in the human — then your answer is philosophically mature.' },
      { text: 'ما أعرف — هذا يربكني.', translation: 'I don\'t know — this confuses me.', nextStepId: 's5', correct: false, feedback: 'Intellectual surrender too early. Sit with the tension — don\'t flee it.' },
      { text: 'الفلاسفة اختلفوا في هذا كثيراً عبر التاريخ.', translation: 'Philosophers have disagreed about this greatly throughout history.', nextStepId: 's5', correct: false, feedback: 'Deflecting to history instead of thinking with him.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'يعني تعيش وكأنك حر، وتعتقد أن ثمة من كتب حريتك؟', translation: 'Meaning you live as if you\'re free, and you believe there\'s one who wrote your freedom?', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'This is the sharpest point in the dialogue. Meet it.', options: [
      { text: 'بالضبط — والله ما فيه تناقض في هذا عندي. الحرية ما تكون معنى إلا لو كانت أمام شيء أكبر.', translation: 'Exactly — by God there\'s no contradiction in this for me. Freedom only has meaning when it stands before something greater.', nextStepId: 's7', correct: true, feedback: 'Philosophically rich and delivered with conviction — this is the mark of someone who has actually thought about this.' },
      { text: 'هذا تناقض صريح لا يمكن التوفيق بينه.', translation: 'This is an explicit contradiction that cannot be reconciled.', nextStepId: 's7', correct: false, feedback: 'You\'re conceding the whole argument. A compatibilist position is entirely defensible.' },
      { text: 'نعم تقريباً — لكنّ التفاصيل معقّدة.', translation: 'Yes approximately — but the details are complicated.', nextStepId: 's7', correct: false, feedback: 'Vague and evasive — you\'re hedging instead of committing to a position.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'خلاص يعني — أنا اخترت أفكّر معاك الليلة، وربما هذا كان مكتوباً. لكن ما يهمّ — جميل.', translation: 'That\'s it then — I chose to think with you tonight, and perhaps that was written. But it doesn\'t matter — it\'s beautiful.', end: true },
  ],
  completionMessage: 'A genuine philosophical exchange with depth and courage. خلاص يعني — بعض الأسئلة تكفيها الشركة.',
},

{
  id: 'saudi_convo_p10_intimate_apology_partner',
  phase: 10,
  title: 'Intimate Apology to Partner',
  description: 'A private, vulnerable apology to your spouse after a hurtful argument.',
  focalWordIds: ['w_qalb', 'w_hubb', 'w_habiib', 'w_ghafara', 'w_wallah', 'w_nafs', 'w_because'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'تكلّم — اللي قلته أمس ما كان صح.', translation: 'Speak — what you said yesterday wasn\'t right.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Own your mistake fully without deflecting.', options: [
      { text: 'والله العظيم — ما قصّدت. بس هذا ما يكفي — اللي قلته كان مؤلم وغلط.', translation: 'By God Almighty — I didn\'t mean it. But that\'s not enough — what I said was hurtful and wrong.', nextStepId: 's3', correct: true, feedback: 'Acknowledging both the intent and the impact — the highest form of apology.' },
      { text: 'كنت متعباً ومضغوطاً يومها.', translation: 'I was tired and under pressure that day.', nextStepId: 's3', correct: false, feedback: 'An explanation that doubles as an excuse. Your partner has heard enough excuses.' },
      { text: 'آسف. أتمنى أن تسامحيني.', translation: 'I\'m sorry. I hope you forgive me.', nextStepId: 's3', correct: false, feedback: 'Too quick and light — a wound this deep needs more than a brief sorry.' },
      { text: 'أنا آسف من أعماق قلبي — حبيبتي ما تستاهل كلامي ذاك أبداً.', translation: 'I\'m sorry from the depths of my heart — my love you didn\'t deserve those words at all.', nextStepId: 's3', correct: true, feedback: 'حبيبتي with the specific acknowledgment of undeservingness — this is real.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'تعرف إيش الأصعب؟ مو الكلام — إن اللي قاله كان أنت. أنت.', translation: 'You know what\'s hardest? Not the words — that the one who said it was you. You.', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Sit with the weight of that without deflecting.', options: [
      { text: 'أعرف. وهذا اللي ما يسامحني فيه قلبي على نفسي.', translation: 'I know. And that\'s what my heart can\'t forgive myself for.', nextStepId: 's5', correct: true, feedback: 'Sitting with the guilt without deflection — this is what genuine remorse looks like.' },
      { text: 'بس أنت تعرف إني ما أقصد.', translation: 'But you know I don\'t mean it.', nextStepId: 's5', correct: false, feedback: 'Appealing to your past character to dismiss the current harm. Wrong move.' },
      { text: 'الكل يخطئ أحياناً.', translation: 'Everyone makes mistakes sometimes.', nextStepId: 's5', correct: false, feedback: 'Universalizing your mistake — another subtle deflection.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'إيش تبي مني الحين؟', translation: 'What do you want from me now?', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Don\'t demand, don\'t perform — be honest about what you need.', options: [
      { text: 'ما أبي شي الحين — بس أبيك تعرفين إن أنا الغلطان وإنك غالية عليّ.', translation: 'I don\'t want anything right now — I just want you to know I\'m in the wrong and that you mean the world to me.', nextStepId: 's7', correct: true, feedback: 'No transaction, just love. This is the answer.' },
      { text: 'أبيك تسامحيني حتى نرجع زي ما كنّا.', translation: 'I want you to forgive me so we can go back to how we were.', nextStepId: 's7', correct: false, feedback: 'Seeking forgiveness for your own comfort, not her healing — the wrong framing.' },
      { text: 'أريد أن نبدأ من جديد.', translation: 'I want us to start fresh.', nextStepId: 's7', correct: false, feedback: 'Too quick — you can\'t skip the pain on the way to the reset.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'أعطيني وقت — مو لأني ما أحبّك. لأني أحبّك وكلامك تعبني.', translation: 'Give me time — not because I don\'t love you. Because I do love you and your words exhausted me.', end: true },
  ],
  completionMessage: 'You made a genuine apology — no deflection, no transaction. Just love and accountability. ما شاء الله.',
},

{
  id: 'saudi_convo_p10_negotiate_inheritance',
  phase: 10,
  title: 'Negotiating Inheritance',
  description: 'A tense but respectful negotiation between siblings about dividing family inheritance.',
  focalWordIds: ['w_haqq', 'w_qaliil', 'w_kathiir', 'w_money', 'w_because', 'w_wallah', 'w_society', 'w_ikhtalafa'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'الحق الشرعي واضح — لكن أنت تعرف إن البيت ما يمكن يُباع. فيه ذكريات.', translation: 'The legal right is clear — but you know the house can\'t be sold. There are memories in it.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Acknowledge the emotional weight while being clear about your rights.', options: [
      { text: 'والله الذكريات لنا جميعاً — وأنا كذلك عندي حق فيها وفي البيت.', translation: 'By God the memories belong to all of us — and I too have a right to them and to the house.', nextStepId: 's3', correct: true, feedback: 'You honour the emotional argument without surrendering your legal position.' },
      { text: 'الذكريات لا علاقة لها بالقانون — نتكلم عن حقوق واضحة.', translation: 'Memories have nothing to do with law — we\'re talking about clear rights.', nextStepId: 's3', correct: false, feedback: 'Dismissing emotions in a family negotiation will collapse the dialogue. Don\'t separate the two.' },
      { text: 'أنا معك — البيت يبقى ولا نبيعه.', translation: 'I\'m with you — the house stays, we won\'t sell it.', nextStepId: 's3', correct: false, feedback: 'You\'re giving in without negotiating — this may not reflect your actual rights.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'إذن ماذا تقترح؟ أنا ما عندي فلوس أشتري نصيبك.', translation: 'So what do you propose? I don\'t have the money to buy your share.', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Offer a fair solution that protects everyone.', options: [
      { text: 'نبقيه مشتركاً — تسكن فيه وتعطيني إيجار نصيبي. نحدد السعر بشكل عادل.', translation: 'We keep it joint — you live in it and pay me rent for my share. We set a fair price.', nextStepId: 's5', correct: true, feedback: 'A practical solution that respects both the emotional and financial dimensions.' },
      { text: 'لازم نبيعه ونقسم الفلوس. هذا الحق.', translation: 'We must sell it and split the money. That\'s the right thing.', nextStepId: 's5', correct: false, feedback: 'Legally correct but emotionally tone-deaf in a family context — will create lasting damage.' },
      { text: 'خلاص يعني — خذ البيت وما أبي شي.', translation: 'That\'s it then — take the house and I want nothing.', nextStepId: 's5', correct: false, feedback: 'Giving up your rights to avoid conflict isn\'t nobility — it breeds resentment later.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'الإيجار؟ هذا بيحوّل البيت لعمل تجاري — كيف أنظر في عيون أولادي؟', translation: 'Rent? That turns the house into a commercial deal — how do I look my children in the eyes?', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Address his dignity concern without abandoning your position.', options: [
      { text: 'يا أخوي — ما يهمّك كيف تنظر لأولادك. المهم كيف تنظر لي أنا. أنا أخوك ومستحق.', translation: 'Brother — don\'t worry about how you look to your children. What matters is how you look to me. I\'m your brother and I\'m owed this.', nextStepId: 's7', correct: true, feedback: 'Brings it back to the sibling relationship — the real stakes. ما يهمّك lands perfectly here.' },
      { text: 'هذا ليس مشكلتي.', translation: 'That\'s not my problem.', nextStepId: 's7', correct: false, feedback: 'Too cold — you\'ll win the argument and lose a brother.' },
      { text: 'لا بأس، نسمّي الأمر بطريقة ثانية إذا كان هذا يريحك.', translation: 'It\'s fine, we can name it differently if that makes you comfortable.', nextStepId: 's7', correct: false, feedback: 'Rebranding doesn\'t solve the underlying tension — address the real concern.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'والله العظيم ما أبي أظلمك. نجلس مع الكبار ونحل هذا بطريقة تحفظ الجميع.', translation: 'I swear to God I don\'t want to wrong you. Let\'s sit with the elders and solve this in a way that protects everyone.', end: true },
  ],
  completionMessage: 'You navigated a charged inheritance negotiation with clarity, dignity, and family warmth. الله يوسّع على الجميع.',
},

{
  id: 'saudi_convo_p10_compliment_poetry',
  phase: 10,
  title: 'Complimenting Poetry',
  description: 'A peer shares their new poem and you offer genuine, textured feedback.',
  focalWordIds: ['w_fikra', 'w_culture', 'w_wallah', 'w_mashallah', 'w_because', 'w_qalb', 'w_nafs'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'قرأت القصيدة الجديدة؟ أبي رأيك الحقيقي — مو المجاملة.', translation: 'Did you read the new poem? I want your real opinion — not flattery.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Give a genuine opening reaction.', options: [
      { text: 'والله — السطر الثالث ضربني. ما توقّعت إنك تجرأ على هذا الصورة.', translation: 'By God — the third line hit me. I didn\'t expect you to dare that image.', nextStepId: 's3', correct: true, feedback: 'Specific and honest — naming a line shows you actually read it closely.' },
      { text: 'ما شاء الله، قصيدة رائعة ومعبّرة جداً.', translation: 'MashaAllah, a wonderful and very expressive poem.', nextStepId: 's3', correct: false, feedback: 'Generic flattery — exactly what he said he didn\'t want.' },
      { text: 'جيدة، لكن بعض الأسطر تحتاج مراجعة.', translation: 'Good, but some lines need revision.', nextStepId: 's3', correct: false, feedback: 'You\'re leading with critique before giving the overall reaction — abrupt.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'السطر الثالث؟ كثير منهم قالوا إنه غامض — إيش شفت فيه أنت؟', translation: 'The third line? Many said it was obscure — what did you see in it?', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Interpret the line with genuine engagement.', options: [
      { text: 'شفت إنك تتكلم عن الغياب — مو الفقد. الفرق دقيق وعميق.', translation: 'I saw you were speaking about absence — not loss. The difference is subtle and deep.', nextStepId: 's5', correct: true, feedback: 'Close literary reading that shows genuine engagement with the text.' },
      { text: 'ما فهمته أنا كذلك — ربما تشرحه؟', translation: 'I didn\'t understand it either — maybe you can explain it?', nextStepId: 's5', correct: false, feedback: 'You\'re asking him to explain his own poem instead of meeting him as a reader. Passive.' },
      { text: 'الغموض في الشعر ليس عيباً بالضرورة.', translation: 'Obscurity in poetry is not necessarily a flaw.', nextStepId: 's5', correct: false, feedback: 'A defensive reflex, not a real response. You\'re not engaging the poem.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'ابن الواوي — أنت الوحيد اللي قرأها صح. والله يعني.', translation: 'Man, you\'re the only one who read it right. By God, seriously.', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Accept the compliment and raise a genuine question.', options: [
      { text: 'شكراً — بس سؤال: النهاية حسّيت إنها مبكّرة. كان عندك مكان تروح؟', translation: 'Thank you — but one question: the ending felt early. Did you have somewhere to go?', nextStepId: 's7', correct: true, feedback: 'Gracious acceptance followed by a real craft question — this is how creative peers talk.' },
      { text: 'شكراً جداً — هذا شرّفني.', translation: 'Thank you very much — this honours me.', nextStepId: 's7', correct: false, feedback: 'You close the exchange when there\'s more to explore.' },
      { text: 'لا — الكثيرون لا يقرأون الشعر بعمق في وقتنا.', translation: 'No — many people don\'t read poetry deeply in our time.', nextStepId: 's7', correct: false, feedback: 'A complaint about readers that dismisses the compliment and deflects from the poem.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'والله — أحسست إن النهاية المبكّرة هي النهاية الوحيدة الصادقة. السكوت قصيدة كذلك.', translation: 'By God — I felt the early ending was the only honest ending. Silence is a poem too.', end: true },
  ],
  completionMessage: 'You gave a poet the gift of being truly read. ما شاء الله على القراءة.',
},

{
  id: 'saudi_convo_p10_intellectual_disagree_professor',
  phase: 10,
  title: 'Disagreeing With Your Professor',
  description: 'You respectfully but firmly challenge your professor\'s position in an academic discussion.',
  focalWordIds: ['w_opinion', 'w_debate', 'w_think', 'w_because', 'w_haqq', 'w_bahth', 'w_fahima'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'الدراسات الكلاسيكية في هذا الحقل تثبت وجهة نظري — لا مجال للجدل.', translation: 'Classical studies in this field prove my point of view — there is no room for debate.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Challenge this with respect and precision.', options: [
      { text: 'مع احترامي يا دكتور — الدراسات الكلاسيكية اعتمدت على عيّنات لا تمثّل السياق الذي نتكلم عنه.', translation: 'With my respect, doctor — the classical studies relied on samples that don\'t represent the context we\'re discussing.', nextStepId: 's3', correct: true, feedback: 'مع احترامي is the right opener — respectful, then precise. Perfect.' },
      { text: 'أنا لا أوافق على هذا الرأي يا دكتور.', translation: 'I disagree with this opinion, doctor.', nextStepId: 's3', correct: false, feedback: 'True but too blunt without substance — you need the argument, not just the disagreement.' },
      { text: 'ربما يا دكتور — بس في رأيي المتواضع...', translation: 'Perhaps, doctor — but in my humble opinion...', nextStepId: 's3', correct: false, feedback: 'The excessive hedging weakens your position before you make it. You have a valid point — own it.' },
      { text: 'الأبحاث الحديثة تعارض هذا يا دكتور — هل اطّلعت على دراسة X؟', translation: 'Recent research contradicts this, doctor — have you seen study X?', nextStepId: 's3', correct: true, feedback: 'Citing recent evidence is a clean academic challenge — it questions the claim, not the person.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'عيّنات؟ تلك الدراسات أُجريت على آلاف الحالات. ما هو مصدرك؟', translation: 'Samples? Those studies were conducted on thousands of cases. What is your source?', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Back your claim with specifics.', options: [
      { text: 'باحثو جامعة X نشروا عام ٢٠٢٢ — المجموعة كانت متجانسة ثقافياً بشكل لا يعكس التنوع اللازم.', translation: 'Researchers at University X published in 2022 — the group was culturally homogeneous in a way that doesn\'t reflect necessary diversity.', nextStepId: 's5', correct: true, feedback: 'Year, institution, specific methodological critique — this is rigorous academic discourse.' },
      { text: 'قرأت عدة مقالات تشير إلى هذا.', translation: 'I read several articles pointing to this.', nextStepId: 's5', correct: false, feedback: 'Vague — \'several articles\' won\'t hold up against a professor\'s methodological challenge.' },
      { text: 'أنا أتكلم من تجربتي الشخصية.', translation: 'I\'m speaking from personal experience.', nextStepId: 's5', correct: false, feedback: 'Personal experience doesn\'t counter empirical research in an academic debate.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'نقطة تستحق الدراسة. لكن ألا ترى أن نقدك يُضعف المنهج بأكمله لا الدراسة فقط؟', translation: 'A point worth studying. But don\'t you see that your critique weakens the entire methodology, not just the study?', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Clarify the scope of your argument.', options: [
      { text: 'هذا تماماً ما أقصده يا دكتور — المنهج بحاجة لمراجعة، لا الاستنتاجات فقط.', translation: 'That\'s exactly what I mean, doctor — the methodology needs review, not just the conclusions.', nextStepId: 's7', correct: true, feedback: 'Accepting the implication and pushing further — intellectually confident.' },
      { text: 'لا، أنا أنتقد الدراسة فقط.', translation: 'No, I\'m only critiquing the study.', nextStepId: 's7', correct: false, feedback: 'You\'re retreating from your strongest position — don\'t.' },
      { text: 'ربما أبالغت في نقدي.', translation: 'Perhaps I exaggerated my critique.', nextStepId: 's7', correct: false, feedback: 'Backing down when under pressure — a common mistake under professorial authority.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'إذن اكتب لي ورقة بحثية عن هذا — ثلاثة آلاف كلمة. سأقرأها بانتباه.', translation: 'Then write me a research paper on this — three thousand words. I\'ll read it carefully.', end: true },
  ],
  completionMessage: 'You challenged a professor with precision, respect, and intellectual courage. هذا هو العقل النقدي.',
},

{
  id: 'saudi_convo_p10_traditional_wedding_speech',
  phase: 10,
  title: 'Traditional Wedding Speech',
  description: 'You deliver or respond to speeches at a traditional Saudi wedding. Navigate formality and warmth.',
  focalWordIds: ['w_wallah', 'w_mashallah', 'w_inshallah', 'w_hubb', 'w_habiib', 'w_family', 'w_yaani'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'يا ضيوف الكرام — نسعد بتشريفكم في هذا اليوم المبارك. نطلب من الأخ كلمة.', translation: 'Honoured guests — we are delighted by your presence on this blessed day. We ask the brother for a word.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Open your wedding speech with the right register.', options: [
      { text: 'بسم الله الرحمن الرحيم — والله يا أهل العريسين، ما في كلام يوصف فرحة هذا اليوم.', translation: 'In the name of God, the Most Gracious, the Most Merciful — by God, family of the two newlyweds, no words can describe the joy of this day.', nextStepId: 's3', correct: true, feedback: 'Opening with bismillah, then expressing inexpressible joy — perfect traditional wedding register.' },
      { text: 'مرحباً بالجميع! اليوم يوم سعيد.', translation: 'Welcome everyone! Today is a happy day.', nextStepId: 's3', correct: false, feedback: 'Too casual for a formal wedding speech. This needs gravitas and warmth together.' },
      { text: 'يسعدني أن أتكلم في هذه المناسبة الكريمة.', translation: 'I\'m pleased to speak on this honourable occasion.', nextStepId: 's3', correct: false, feedback: 'Too formal and bureaucratic — a wedding needs warmth, not corporate diction.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'جزاك الله خيراً — كمّل يا رجل، الكل يستمع.', translation: 'May God reward you with goodness — continue, man, everyone is listening.', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Address the couple directly with advice and blessing.', options: [
      { text: 'يا عريسين — الزواج ما هو لحظة، هو قرار تجدّدونه كل يوم. والله يوفّقكم ويجمعكم على خير.', translation: 'Dear newlyweds — marriage is not a moment, it\'s a decision you renew every day. May God grant you success and unite you in goodness.', nextStepId: 's5', correct: true, feedback: 'Wisdom and dua in one — the traditional combination for a wedding.' },
      { text: 'أتمنى لكما السعادة الزوجية الدائمة.', translation: 'I wish you both permanent marital happiness.', nextStepId: 's5', correct: false, feedback: 'Generic well-wishing without depth or warmth — could be a card message.' },
      { text: 'تذكّرا دائماً أن الحياة فيها صعاب.', translation: 'Always remember that life has hardships.', nextStepId: 's5', correct: false, feedback: 'Wrong tone for a wedding speech — don\'t lead with the difficult reality at the wedding feast.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'ما شاء الله — على بال العيلتين الحقيقيتين دايماً. شكراً على الكلام الطيب.', translation: 'MashaAllah — both families are always in our hearts. Thank you for the kind words.', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Close the speech with a final blessing.', options: [
      { text: 'الله يبارك لكم ويبارك عليكم ويجمع بينكم في خير — وربنا يتمّم بالخير ويرزقهم الذريّة الصالحة.', translation: 'May God bless you and bless upon you and unite you in goodness — and may our Lord complete in goodness and grant them righteous offspring.', nextStepId: 's7', correct: true, feedback: 'The traditional wedding dua in full — this is exactly what the moment calls for.' },
      { text: 'أتمنى لكم جميعاً مساء سعيداً.', translation: 'I wish you all a happy evening.', nextStepId: 's7', correct: false, feedback: 'You\'re ending like a hotel host, not a family member at a wedding.' },
      { text: 'شكراً على استماعكم.', translation: 'Thank you for listening.', nextStepId: 's7', correct: false, feedback: 'A public-speaking cliché that completely deflates the moment.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'آمين آمين — بارك الله فيك وفي لسانك. ما شاء الله عليك يا خطيب!', translation: 'Amen, amen — may God bless you and your tongue. MashaAllah on you, speaker!', end: true },
  ],
  completionMessage: 'You delivered a wedding speech with tradition, warmth, and the right register. بارك الله في الجميع!',
},

{
  id: 'saudi_convo_p10_returning_home_after_years',
  phase: 10,
  title: 'Returning Home After Years',
  description: 'You\'ve been away for years and return home. Navigate the emotions, changes, and belonging.',
  focalWordIds: ['w_tadhakkara', 'w_remember', 'w_bayt', 'w_wallah', 'w_khalas', 'w_yaani', 'w_hayaa'],
  steps: [
    { id: 's1', speaker: 'partner', text: 'رجعت يا غالي! والله العظيم كأنك ما غبت — بس وجهك أكبر.', translation: 'You came back, dear! By God Almighty it\'s as if you never left — but your face has matured.', next: 's2' },
    { id: 's2', speaker: 'user', prompt: 'Respond to the homecoming with genuine emotion.', options: [
      { text: 'والله يا عمي — ما صدّقت إني رجعت. الهواء نفسه ريحته مختلفة هنا.', translation: 'By God, man — I can\'t believe I\'m back. The very air smells different here.', nextStepId: 's3', correct: true, feedback: 'Sensory and emotional — the smell of home is a universally understood detail that lands perfectly.' },
      { text: 'نعم، عدت أخيراً. الرحلة كانت مرهقة.', translation: 'Yes, I returned at last. The trip was exhausting.', nextStepId: 's3', correct: false, feedback: 'Opening with the logistics of travel instead of the emotion of return. Wrong priority.' },
      { text: 'أهلاً. كيف الأحوال؟', translation: 'Hello. How are things?', nextStepId: 's3', correct: false, feedback: 'Far too flat for a homecoming after years away. Your friend is overwhelmed — match him.' },
      { text: 'خلاص يعني — رجعت. ما أعرف كيف أوصف اللي أحسّ فيه الحين.', translation: 'That\'s it then — I\'m back. I don\'t know how to describe what I\'m feeling right now.', nextStepId: 's3', correct: true, feedback: 'خلاص يعني used beautifully — the exhale of arrival, the inexpressibility of return.' },
    ]},
    { id: 's3', speaker: 'partner', text: 'ابن الواوي — كم شيء تغيّر! البيت اللي كنّا نلعب فيه صار عمارة.', translation: 'Man — how much has changed! The house we used to play in became a building.', next: 's4' },
    { id: 's4', speaker: 'user', prompt: 'Respond to the change with the right mix of nostalgia and acceptance.', options: [
      { text: 'على بال تلك الأيام — بس الأماكن تتغيّر والذكريات ما تتغيّر.', translation: 'Those days are still on my heart — but places change, memories don\'t.', nextStepId: 's5', correct: true, feedback: 'على بال is used perfectly here — and the insight about places vs memories is beautiful.' },
      { text: 'نعم، التطوير العمراني سريع جداً هنا.', translation: 'Yes, urban development is very fast here.', nextStepId: 's5', correct: false, feedback: 'Too analytical and cold for a moment of homecoming emotion.' },
      { text: 'هذا مؤسف — كان يجب الحفاظ على التراث العمراني.', translation: 'That\'s unfortunate — the architectural heritage should have been preserved.', nextStepId: 's5', correct: false, feedback: 'Turning your homecoming into an urban planning complaint.' },
    ]},
    { id: 's5', speaker: 'partner', text: 'صح والله. بس أنت — تغيّرت ولا نفس الشخص؟', translation: 'True by God. But you — did you change or are you the same person?', next: 's6' },
    { id: 's6', speaker: 'user', prompt: 'Answer this honestly — the most personal question of the conversation.', options: [
      { text: 'والله — تغيّرت بالخارج. بس الجوف — الجوف نفسه. وهذا البيت هو اللي يثبت هذا.', translation: 'By God — I changed on the outside. But the inside — the inside is the same. And this home is what proves it.', nextStepId: 's7', correct: true, feedback: 'The inside/outside distinction with the home as proof — poetic and deeply Saudi.' },
      { text: 'نعم، تغيّرت كثيراً بسبب التجارب والسفر.', translation: 'Yes, I changed a lot because of experiences and travel.', nextStepId: 's7', correct: false, feedback: 'True but abstract — the personal moment calls for something more specific and felt.' },
      { text: 'لا، ما تغيّرت — أنا نفسي.', translation: 'No, I didn\'t change — I\'m the same.', nextStepId: 's7', correct: false, feedback: 'Too simple and defensive — a person who\'s lived away for years has changed. Own it with nuance.' },
    ]},
    { id: 's7', speaker: 'partner', text: 'خلاص يعني — أهلاً بك في البيت يا عمي. ما تسافر كذا بعد.', translation: 'That\'s it then — welcome home, man. Don\'t travel away like that again.', end: true },
  ],
  completionMessage: 'You navigated a homecoming with real emotional depth and idiomatic precision. أهلاً وسهلاً — Welcome home!',
},
